name:  resource_group

on:
  push:
    branches:
      - main
      - rg

  pull_request:
    branches:
      - main

permissions:
  contents: read

env:
  TF_VERSION: "1.9.8"
  working-directory: ./environment/dev

  
  ARM_CLIENT_ID: "076a5682-82e0-4c00-b9f5-38d0a4b55aad"
  ARM_CLIENT_SECRET: "o~G8Q~3vAGgANwcoCPWddzMiIUZ99MbInMB7vdAt"
  ARM_TENANT_ID: "1d6a29b8-43b7-4c79-9bdf-c48c5d9b44dd"
  ARM_SUBSCRIPTION_ID: "111116e2-8386-4181-b026-d821502e31cc"
  ARM_USE_CLI: "false"

jobs:

  # ============================================================
  # FEATURE BRANCH
  # Terraform Format + Init + Validate + Plan
  # ============================================================

  terraform-feature:
    name: Terraform Plan - Feature
    if: startsWith(github.ref, 'refs/heads/feature/') || github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # --------------------------------------------------------
      # Terraform Setup
      # --------------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # --------------------------------------------------------
      # Azure Login - Client Secret
      # --------------------------------------------------------

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: |
            {
              "clientId": "076a5682-82e0-4c00-b9f5-38d0a4b55aad",
              "clientSecret": "o~G8Q~3vAGgANwcoCPWddzMiIUZ99MbInMB7vdAt",
              "subscriptionId": "111116e2-8386-4181-b026-d821502e31cc",
              "tenantId": "1d6a29b8-43b7-4c79-9bdf-c48c5d9b44dd"
            }

      - name: Check Azure Login
        run: az account show

      # --------------------------------------------------------
      # Terraform Format
      # --------------------------------------------------------

      - name: Terraform Format Check
        working-directory: ./environment/dev
        run: terraform fmt -check -recursive

      # --------------------------------------------------------
      # Terraform Init
      # --------------------------------------------------------

      - name: Terraform Init
        working-directory: ./environment/dev
        run: terraform init -reconfigure

      # --------------------------------------------------------
      # Terraform Validate
      # --------------------------------------------------------

      - name: Terraform Validate
        working-directory: ./environment/dev
        run: terraform validate

      # --------------------------------------------------------
      # Terraform Plan
      # --------------------------------------------------------

      - name: Terraform Plan
        working-directory: ./environment/dev
        run: terraform plan -out=tfplan


  # ============================================================
  # MAIN BRANCH
  # Terraform Format + Init + Validate + Plan + Apply
  # ============================================================

  terraform-main:
    name: Terraform Plan and Apply - Main
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # --------------------------------------------------------
      # Terraform Setup
      # --------------------------------------------------------

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      # --------------------------------------------------------
      # Azure Login - Client Secret
      # --------------------------------------------------------

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: |
            {
              "clientId": "076a5682-82e0-4c00-b9f5-38d0a4b55aad",
              "clientSecret":  "o~G8Q~3vAGgANwcoCPWddzMiIUZ99MbInMB7vdAt",
              "subscriptionId": "111116e2-8386-4181-b026-d821502e31cc",
              "tenantId": "1d6a29b8-43b7-4c79-9bdf-c48c5d9b44dd"
              }

      - name: Check Azure Login
        run: az account show


      # --------------------------------------------------------
      # Terraform Format
      # --------------------------------------------------------

      - name: Terraform Format Check
        working-directory: ./environment/dev
        run: terraform fmt -check -recursive

      # --------------------------------------------------------
      # Terraform Init
      # --------------------------------------------------------

      - name: Terraform Init
        working-directory: ./environment/dev
        run: terraform init -reconfigure

      # --------------------------------------------------------
      # Terraform Validate
      # --------------------------------------------------------

      - name: Terraform Validate
        working-directory: ./environment/dev
        run: terraform validate

      # --------------------------------------------------------
      # Terraform Plan
      # --------------------------------------------------------

      - name: Terraform Plan
        working-directory: ./environment/dev
        run: terraform plan -out=tfplan

      # --------------------------------------------------------
      # Terraform Apply
      # --------------------------------------------------------

      - name: Terraform Apply
        working-directory: ./environment/dev
        run: terraform apply -auto-approve tfplan

